---
title: "Covid91 vaccine study Final2023"
author: "Lisa Davis"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalData <-read.csv(file="final.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalData  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
```

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

$H_0$: The covid-19 vaccine (drug) is not effective among the subgroup users.
$H_A$: The covid-19 vaccine (drug) is effective among non subgroup users.

## Males

### Introduction

$H_0$: The vaccine is not effective in preventing covid-19 in males.

$H_A$: The vaccine is effective in preventing covid-19 in males.

The data i used for this clinical test, came from a final data file provided by professor Brownlow. 


### Methods



### Results

#### Descriptive results

##### Graphical results

##### Numerical results

##### Inferencial results

### Discussion and conclusion



## Females

### Introduction

### Methods

### Results

#### Descriptive results

##### Graphical results

##### Numerical results

##### Inferencial results

### Discussion and conclusion



## LGBTQ

### Introduction

### Methods

### Results

#### Descriptive results

##### Graphical results

##### Numerical results

##### Inferencial results

### Discussion and conclusion



## Druggies

### Introduction

### Methods

### Results

#### Descriptive results

##### Graphical results

##### Numerical results

##### Inferencial results

### Discussion and conclusion



# Overall Results and Conclusions

### Introduction

### Methods

### Results

#### Descriptive results

##### Graphical results

##### Numerical results

##### Inferencial results

### Discussion and conclusion

